// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dicemix.proto

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	dicemix.proto

It has these top-level messages:
	PeerInfo
	CoinJoinReq
	CoinJoinRes
	KeyExchangeReq
	KeyExchangeRes
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PeerInfo struct {
	PeerId uint32 `protobuf:"varint,1,opt,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	Pk     []byte `protobuf:"bytes,2,opt,name=pk,proto3" json:"pk,omitempty"`
}

func (m *PeerInfo) Reset()                    { *m = PeerInfo{} }
func (m *PeerInfo) String() string            { return proto.CompactTextString(m) }
func (*PeerInfo) ProtoMessage()               {}
func (*PeerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PeerInfo) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *PeerInfo) GetPk() []byte {
	if m != nil {
		return m.Pk
	}
	return nil
}

type CoinJoinReq struct {
}

func (m *CoinJoinReq) Reset()                    { *m = CoinJoinReq{} }
func (m *CoinJoinReq) String() string            { return proto.CompactTextString(m) }
func (*CoinJoinReq) ProtoMessage()               {}
func (*CoinJoinReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CoinJoinRes struct {
	SessionId uint32   `protobuf:"varint,2,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	PeerId    uint32   `protobuf:"varint,3,opt,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	PeerIds   []uint64 `protobuf:"varint,4,rep,packed,name=peer_ids,json=peerIds" json:"peer_ids,omitempty"`
}

func (m *CoinJoinRes) Reset()                    { *m = CoinJoinRes{} }
func (m *CoinJoinRes) String() string            { return proto.CompactTextString(m) }
func (*CoinJoinRes) ProtoMessage()               {}
func (*CoinJoinRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CoinJoinRes) GetSessionId() uint32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *CoinJoinRes) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *CoinJoinRes) GetPeerIds() []uint64 {
	if m != nil {
		return m.PeerIds
	}
	return nil
}

type KeyExchangeReq struct {
	SessionId uint32 `protobuf:"varint,2,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	PeerId    uint32 `protobuf:"varint,3,opt,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	Pk        []byte `protobuf:"bytes,4,opt,name=pk,proto3" json:"pk,omitempty"`
}

func (m *KeyExchangeReq) Reset()                    { *m = KeyExchangeReq{} }
func (m *KeyExchangeReq) String() string            { return proto.CompactTextString(m) }
func (*KeyExchangeReq) ProtoMessage()               {}
func (*KeyExchangeReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *KeyExchangeReq) GetSessionId() uint32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *KeyExchangeReq) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *KeyExchangeReq) GetPk() []byte {
	if m != nil {
		return m.Pk
	}
	return nil
}

type KeyExchangeRes struct {
	SessionId uint32      `protobuf:"varint,2,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	PeerId    uint32      `protobuf:"varint,3,opt,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	Peers     []*PeerInfo `protobuf:"bytes,4,rep,name=peers" json:"peers,omitempty"`
}

func (m *KeyExchangeRes) Reset()                    { *m = KeyExchangeRes{} }
func (m *KeyExchangeRes) String() string            { return proto.CompactTextString(m) }
func (*KeyExchangeRes) ProtoMessage()               {}
func (*KeyExchangeRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *KeyExchangeRes) GetSessionId() uint32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *KeyExchangeRes) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *KeyExchangeRes) GetPeers() []*PeerInfo {
	if m != nil {
		return m.Peers
	}
	return nil
}

func init() {
	proto.RegisterType((*PeerInfo)(nil), "messages.PeerInfo")
	proto.RegisterType((*CoinJoinReq)(nil), "messages.CoinJoinReq")
	proto.RegisterType((*CoinJoinRes)(nil), "messages.CoinJoinRes")
	proto.RegisterType((*KeyExchangeReq)(nil), "messages.KeyExchangeReq")
	proto.RegisterType((*KeyExchangeRes)(nil), "messages.KeyExchangeRes")
}

func init() { proto.RegisterFile("dicemix.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x55, 0xdc, 0xd0, 0x86, 0x2b, 0xe9, 0xe0, 0x85, 0x30, 0x20, 0x45, 0x9e, 0x3c, 0x65, 0xa0,
	0x3f, 0x01, 0x31, 0x04, 0x16, 0xe4, 0x89, 0x0d, 0x4a, 0x7d, 0x14, 0xab, 0x8a, 0xed, 0xf8, 0x18,
	0xc2, 0xbf, 0x47, 0x89, 0x13, 0x14, 0x18, 0xb3, 0xf9, 0xf9, 0x59, 0xef, 0xcb, 0x90, 0x6b, 0x73,
	0xc4, 0xc6, 0x74, 0x95, 0x0f, 0xee, 0xcb, 0xf1, 0xac, 0x41, 0xa2, 0xc3, 0x09, 0x49, 0xec, 0x21,
	0x7b, 0x46, 0x0c, 0xb5, 0xfd, 0x70, 0xfc, 0x1a, 0x36, 0x1e, 0x31, 0xbc, 0x1a, 0x5d, 0x24, 0x65,
	0x22, 0x73, 0xb5, 0xee, 0x61, 0xad, 0xf9, 0x0e, 0x98, 0x3f, 0x17, 0xac, 0x4c, 0xe4, 0x95, 0x62,
	0xfe, 0x2c, 0x72, 0xd8, 0xde, 0x3b, 0x63, 0x1f, 0x9d, 0xb1, 0x0a, 0x5b, 0xf1, 0x36, 0x87, 0xc4,
	0x6f, 0x01, 0x08, 0x89, 0x8c, 0xb3, 0xbd, 0x12, 0x1b, 0x94, 0x2e, 0xc7, 0x9b, 0x5a, 0xcf, 0x5d,
	0x56, 0x7f, 0x5c, 0x6e, 0x20, 0x1b, 0x09, 0x2a, 0xd2, 0x72, 0x25, 0x53, 0xb5, 0x89, 0x0c, 0x89,
	0x17, 0xd8, 0x3d, 0xe1, 0xf7, 0x43, 0x77, 0xfc, 0x3c, 0xd8, 0x13, 0x2a, 0x6c, 0x17, 0x9b, 0xc4,
	0x2a, 0xe9, 0x6f, 0x95, 0xf0, 0x4f, 0x79, 0x79, 0x7c, 0x09, 0x17, 0xfd, 0x29, 0x66, 0xdf, 0xde,
	0xf1, 0x6a, 0xda, 0xb8, 0x9a, 0x06, 0x56, 0xf1, 0xc1, 0xfb, 0x7a, 0xf8, 0x84, 0xfd, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x53, 0x4b, 0xf0, 0xe4, 0x95, 0x01, 0x00, 0x00,
}
